#ifndef DAC_JUKU_INTERNAL_H
#define DAC_JUKU_INTERNAL_H
/* Internal compatibility state; not a stable public ABI. */
#include "juku.h"
#include "../../third_party/cpu/i8080/i8080.h"
#include "juk_disk.h"
#include "juku_fdc.h"
#include "../../common/trace/trace.h"
#define MEM_SIZE 0x10000u
#define ROM_SIZE 0x4000u
#define CART_SIZE 0x8000u
#define VRAM_BASE 0xD800u
#define VID_DEFAULT_STRIDE 40
#define VID_DEFAULT_LINES 241
#define CONSOLE_QUEUE 4096
#define KBD_HOLD 3
#define KBD_GAP 3
#define KBD_NONE 0xCF

typedef struct {
 void *user;
 int (*serial_read)(void *, void *, size_t);
 int (*serial_write)(void *, uint8_t);
 int (*serial_wait)(void *, int);
 void (*memory_read)(void *, uint16_t, uint8_t);
 void (*log)(void *, const char *);
 void (*frame)(void *, unsigned long);
} juku_hooks;
typedef struct {
  uint16_t count_register;
  uint16_t write_latch;
  uint16_t output_latch;
  uint8_t access;
  uint8_t write_phase;
  uint8_t read_phase;
  uint8_t latch_valid;
  uint8_t bcd;
  uint8_t mode;
} pit_counter;
typedef struct {
  int enabled;
  int expect_mode;
  uint8_t mode_word;
  uint8_t command;
  uint8_t rx_data;
  uint8_t rx_errors;
  uint8_t tx_data;
  uint8_t tx_shift_data;
  int rx_ready;
  int tx_holding_full;
  int tx_busy;
  int fault_tx_stuck;
  int fault_tx_stuck_permanent;
  int fault_tx_stuck_once_enabled;
  int fault_tx_stuck_once_fired;
  uint8_t fault_tx_stuck_once_value;
  int fault_tx_not_ready_once_after_enabled;
  unsigned long fault_tx_not_ready_once_after;
  int fault_tx_empty_low_after_enabled;
  unsigned long fault_tx_empty_low_after;
  int fault_rx_irq_delay_once_enabled;
  int fault_rx_irq_delay_once_fired;
  unsigned long fault_rx_irq_delay_once_after;
  unsigned long fault_rx_irq_delay_cycles;
  unsigned long fault_rx_irq_delay_until;
  unsigned long fault_tx_stuck_once_recoveries;
  unsigned long tx_transfer_cyc;
  unsigned long tx_complete_cyc;
  unsigned long rx_next_cyc;
  unsigned long transfer_cycles;
  unsigned long byte_cycles;
  unsigned long tx_bytes;
  unsigned long rx_bytes;
  unsigned long rx_overruns;
  unsigned long rx_overruns_at_all_ram;
  int all_ram_seen;
  unsigned long rx_disabled_bytes;
} juku_usart;
struct juku {
  i8080 cpu;
  unsigned long frame_cyc, next_frame;
  juku_hooks hooks;
  dac_trace_sink bus_trace;
  uint8_t rom[16384];
  uint8_t cart[32768];
  uint8_t ram[65536];
  int mode;
  uint8_t portc;
  unsigned int video_stride;
  unsigned int video_lines;
  unsigned int video_modx_sequence;
  unsigned int video_stock_sequence;
  unsigned int video_64_sequence;
  int video_modx_mode;
  unsigned int video_console_mode;
  uint8_t kbd_s21_config;
  juk_disk disk;
  juku_fdc fdc;
  int fdc_enabled;
  int fdc_bus_invert;
  int cart_enabled;
  int rom_consecutive_a12_low;
  unsigned int rom_read_burst_count;
  int cpu_a12_increment_fault;
  int cpu_a12_increment_fault_arm_enabled;
  int cpu_a12_increment_fault_arm_fired;
  uint16_t cpu_a12_increment_fault_arm_pc;
  int cpu_a12_increment_fault_arm_bank_mode;
  int cpu_a12_increment_fault_disarm_enabled;
  int cpu_a12_increment_fault_disarm_fired;
  uint16_t cpu_a12_increment_fault_disarm_pc;
  int exec_byte_fault_enabled;
  uint16_t exec_byte_fault_addr;
  uint8_t exec_byte_fault_value;
  unsigned long out_count[256];
  unsigned long in_count[256];
  uint8_t out_last[256];
  int out_seen[256];
  int in_seen[256];
  unsigned long wpage[256];
  unsigned long mode_switches;
  unsigned long fdc_data_reads;
  unsigned long stop_fdc_data_reads;
  unsigned long fdc_last_cyc;
  int timing_log;
  int io_trace;
  int bank_trace;
  int watch_address;
  int watch_address_end;
  unsigned long watch_write_count;
  uint16_t watch_write_previous_address;
  uint8_t watch_write_previous_value;
  uint16_t watch_write_previous_pc;
  unsigned long watch_write_previous_cycle;
  uint16_t watch_write_last_address;
  uint8_t watch_write_last_value;
  uint16_t watch_write_last_pc;
  unsigned long watch_write_last_cycle;
  int ram_fault_enabled;
  uint16_t ram_fault_addr;
  uint8_t ram_fault_stuck_low;
  uint8_t ram_fault_stuck_high;
  int ram_fault_all;
  int ram_drop_write_enabled;
  uint16_t ram_drop_write_addr;
  uint8_t ram_drop_write_value;
  unsigned int ram_drop_write_remaining;
  int ram_alias_enabled;
  uint8_t ram_alias_page_a;
  uint8_t ram_alias_page_b;
  unsigned long dram_retention_cycles;
  unsigned long dram_last_refresh[128];
  int dram_retention_armed;
  int dram_retention_arm_pc_enabled;
  uint16_t dram_retention_arm_pc;
  unsigned long dram_decay_count;
  uint8_t dram_coverage_seen[128];
  unsigned int dram_coverage_count;
  unsigned long dram_coverage_start;
  int dram_full_coverage_reported;
  int pic_fault_enabled;
  uint8_t pic_fault_stuck_low;
  uint8_t pic_fault_stuck_high;
  int ppi_fault_enabled;
  uint8_t ppi_fault_port;
  uint8_t ppi_fault_stuck_low;
  uint8_t ppi_fault_stuck_high;
  int pit_fault_enabled;
  uint8_t pit_fault_port;
  uint8_t pit_fault_stuck_low;
  uint8_t pit_fault_stuck_high;
  pit_counter pit_counters[3][3];
  juku_usart usart;
  int usart_pit_clock;
  unsigned long usart_pit_cpu_hz;
  unsigned long usart_pit_divisor;
  int usart_pit_clock_valid;
  int usart_tx_irq_armed;
  int usart_tx_irq_level;
  int usart_rx_irq_level;
  int usart_tx_irq_pending;
  int usart_rx_irq_pending;
  int usart_host_sync_armed;
  int usart_host_sync_waiting;
  int usart_host_sync_ms;
  unsigned long g_vw;
  unsigned long g_vw_limit;
  unsigned long tpa_opcode_fetches;
  unsigned long tpa_z80_prefix_fetches;
  unsigned long tpa_undocumented_opcode_fetches;
  unsigned long checkpoint_generation;
  unsigned long tpa_program_starts;
  uint16_t tpa_program_entry_sp;
  uint16_t tpa_program_stack_anchor_sp;
  uint16_t tpa_program_stack_low_sp;
  uint16_t tpa_program_current_stack_anchor_sp;
  uint16_t tpa_program_segment_min_anchor_sp;
  uint16_t tpa_program_segment_max_anchor_sp;
  unsigned int tpa_program_stack_segments;
  unsigned int tpa_program_stack_bytes;
  unsigned int tpa_program_explicit_sp_writes;
  unsigned int tpa_program_call_depth;
  uint16_t tpa_program_bdos_return_pc;
  int tpa_program_in_bdos;
  int tpa_program_bdos_tail_call;
  int tpa_program_seen;
  unsigned long tpa_measurement_generation;
  int tpa_measurement_controlled;
  int tpa_measurement_armed;
  int tpa_measurement_frozen;
  uint8_t pic_icw1;
  uint8_t pic_icw2;
  uint8_t pic_mask;
  int pic_expect_icw2;
  unsigned long usart_rx_irq_count;
  unsigned long usart_tx_irq_count;
  unsigned long frame_irq_count;
  char console_queue[4096];
  int console_len;
  int console_visible_len;
  const char * kbd_str;
  int kbd_pos;
  int kbd_phase;
  int live_keyboard;
  uint8_t live_key;
  int kbd_enabled;
  uint8_t kbd_col;
  unsigned long kbd_start_vram;
  int kbd_hold_frames;
  int kbd_gap_frames;
  int kbd_trace;
  int kbd_pc_trigger_enabled;
  int kbd_pc_trigger_fired;
  int kbd_pc_trigger_active;
  int kbd_pc_trigger_hold_frames;
  uint16_t kbd_pc_trigger_pc;
  char kbd_pc_trigger_char;
  int kbd_pc_trigger_gate_enabled;
  uint16_t kbd_pc_trigger_gate_address;
  uint8_t kbd_pc_trigger_gate_value;
};
int juku_is_pit_data_port(juku *ctx, uint8_t port);
pit_counter* juku_pit_counter_for_port(juku *ctx, uint8_t port);
void juku_pit_write(juku *ctx, uint8_t port, uint8_t value);
void juku_video_observe_pit_write(juku *ctx, uint8_t port, uint8_t value);
uint8_t juku_pit_read(juku *ctx, uint8_t port);
void juku_pit_init(juku *ctx);
uint8_t juku_apply_ram_fault(juku *ctx, uint16_t address, uint8_t value);
uint16_t juku_map_ram_address(juku *ctx, uint16_t address);
uint8_t juku_dram_row_from_address(juku *ctx, uint16_t address);
void juku_dram_touch(juku *ctx, i8080* cpu, uint16_t physical_address);
unsigned long juku_pit_effective_divisor(juku *ctx, const pit_counter* counter);
void juku_usart_update_pit_timing(juku *ctx);
void juku_usart_update_irq_edges(juku *ctx);
void juku_usart_reset(juku *ctx);
void juku_usart_poll(juku *ctx, unsigned long cyc);
uint8_t juku_usart_status(juku *ctx);
uint8_t juku_usart_read(juku *ctx, int control, unsigned long cyc);
void juku_usart_write(juku *ctx, int control, uint8_t value, unsigned long cyc);
void juku_set_mode(juku *ctx, int m);
int juku_overlay(juku *ctx, uint16_t a, unsigned* idx);
void juku_trace_bus_event(juku *ctx, const char* kind, uint16_t address, uint8_t data);
uint8_t juku_peek_byte(juku *ctx, uint16_t address);
uint16_t juku_peek_word(juku *ctx, uint16_t address);
uint8_t juku_rb(juku *ctx, void* u, uint16_t a);
char juku_kbd_current_char(juku *ctx);
int juku_vram_pixel(juku *ctx, int x, int y);
int juku_ekdos_prompt_visible(juku *ctx);
uint8_t juku_kbd_portb(juku *ctx, const i8080* cpu);
void juku_wb(juku *ctx, void* u, uint16_t a, uint8_t v);
int juku_take_pic_irq(juku *ctx, i8080* cpu, unsigned irq, const char* source,
                        unsigned long* log_count);
void juku_sync_fdc_time(juku *ctx, i8080* cpu);
uint8_t juku_pin(juku *ctx, void* u, uint8_t p);
void juku_pout(juku *ctx, void* u, uint8_t p, uint8_t v);
void juku_log(juku*, const char*, ...);
#endif
